<?php


class szponzoralt extends Hirek
{
   private $url;

    /**
     * @param mixed $url
     */
    public function setUrl($url)
    {
        $this->url = $url;
        return $this;
    }

    public function HtmlEloNezet()
    {
        $html='<div>';
        $html.='<span>Szponzorált tartalom</span>';
        $html.= parent::HtmlEloNezet(); // TODO: Change the autogenerated stub
        $html.=('<a href="'.$this->url.'"target="_blank">Megtekint</a>');
        $html.='</div>';
        return $html;
    }


}